name: Auto-update Casks
on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tap
        uses: actions/checkout@v6

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update PixelPerfect
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          brew bump-cask-pr \
            --no-fork \
            --no-browse \
            --message "Update PixelPerfect to latest version" \
            --tap ${{ github.repository }} \
            pixelperfect
