name: Auto-update Casks
on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tap
        uses: actions/checkout@v6

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Update PixelPerfect
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
          HOMEBREW_NO_DEV_CMD_WARNING: "1"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          VERSION=$(curl -sL \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "User-Agent: GitHub-Actions" \
            https://api.github.com/repos/cormiertyshawn895/PixelPerfect/releases/latest | jq -r '.tag_name')

          CURRENT_VERSION=$(grep -Po 'version "\K[^"]+' Casks/pixelperfect.rb)

          if [ "$VERSION" == "$CURRENT_VERSION" ]; then
            echo "PixelPerfect is already up to date ($VERSION)."
            exit 0
          fi

          brew bump-cask-pr \
            --version "$VERSION" \
            --no-fork \
            --no-browse \
            --message "Update PixelPerfect to $VERSION" \
            ${{ github.repository }}/pixelperfect
