name: Auto-update Casks
on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tap
        uses: actions/checkout@v6

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          debug: false
        env:
          HOMEBREW_NO_AUTO_UPDATE: "1"
          HOMEBREW_NO_INSTALL_FROM_API: ""
          HOMEBREW_NO_ENV_HINTS: "1"

      - name: Update PixelPerfect
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          cask: pixelperfect
          tap: ${{ github.repository }}
          livecheck: true
          force: true
          no_fork: true
